service: zendesk-clubhouse-adapter

provider:
  name: google
  runtime: go111
  project: infuseai-dev
  # The GCF credentials can be a little tricky to set up. Luckily we've documented this for you here:
  # https://serverless.com/framework/docs/providers/google/guide/credentials/
  #
  # the path to the credentials file needs to be absolute
  credentials: ~/.gcloud/infuseai-dev.json

plugins:
  - serverless-google-cloudfunctions
package:
  exclude:
    - .gitignore
    - .git/**
    - .idea/**
    - test/**
    - .github
    - .npmignore

functions:
  ZendeskClubhouseAdapter:
    handler: ZendeskClubhouseAdapter
    events:
      - http: path
    environment:
      CH_TOKEN: ${env:CH_TOKEN}
      AUTH_USER: ${env:AUTH_USER}
      AUTH_PASSWORD: ${env:AUTH_PASSWORD}
